# Remove the version line completely or use version: "3.8" at the top
version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: smartresume-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: smartresume_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"  # Make sure this line is correct
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password  # Important for MySQL 8

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: smartresume-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8088:80"
    depends_on:
      - mysql

volumes:
  mysql-data: